# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_log_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logNote',
            field=models.TextField(),
        ),
    ]
